<?php
/**
 * ILIAS REST Plugin for the ILIAS LMS
 *
 * Authors: D.Schaefer, T.Hufschmidt <(schaefer|hufschmidt)@hrz.uni-marburg.de>
 * Since 2014
 */
namespace RESTController\extensions\umr_v1;


// This allows us to use shortcuts instead of full quantifier
use \RESTController\libs as Libs;


/**
 * Class GotoLink
 *  This model provides methods to generate permanent-links
 *  to ILIAS-Objects as well as functions to creat new
 *  ILIAS-Sessions on the server while also fetching
 *  the authentification-cookies usable by a web-client.
 */
class GotoLink extends Libs\RESTModel {
  /**
   * Function: getLink($refId, $type)
   *  Generate a permanent-link from given Reference-Id and Object-Type.
   *
   * Parameters:
   *  $refId <Integer> - Reference-Id of requests resource
   *  $type <String> - Object-Type of requested object
   *
   * Return:
   *  <String> - Permament-link to resource given by Reference-Id
   */
  public static function getLink($refId, $type) {
    // Generate link from refId and object-type
    include_once './Services/Link/classes/class.ilLink.php';
    return \ilLink::_getLink($refId, $type);
  }


  /**
   * Function: createSession($username)
   *  Create a new session on the side of ILIAS,
   *  this maily means generating a new entry
   *  in the usr_session table that cen be used
   *  together with a client-side cookie to authenticate
   *  a user.
   *
   * Note:
   *  This call also generates cookie-headers that
   *  will tell the client-side to create those cookies,
   *  but this does not play well with how Slim manages
   *  responses in general.
   *  (Either die() or use self::getSessionCookies())
   *
   * Parameters:
   *  $username <String> - The login-name of the user who's session should be created
   */
  public static function createSession($userName) {
    // Init authentification
    require_once('Services/Authentication/classes/class.ilAuthUtils.php');
    \ilAuthUtils::_initAuth();

    // Authenticate user (this will generate a session in usr_session and send PHPSESSID cookie)
    global $ilAuth;
    $ilAuth->setAuth($userName);
    $ilAuth->start();

    // TODO: Check if there is already an existent/stored session -> delete old one (otherwise database could get bloated!)
  }


  /**
   * Function: getSessionCookies()
   *  Extracts the cookie-header generated by $ilAuth
   *  such that they can be send via Slim instead.
   *  [die() 'ing works also, but seems to be bad practice...]
   *
   * Note:
   *  Should return 'PHPSESSID' and 'authchallenge' cookie.
   *
   * Return:
   *  <Array[
   *   key <String> - Name of session-cookie
   *   value <String> - Value of session-cookie
   *   expires <Number> - Expirition-date of session-cookie
   *   path <String> -  path of session-cookie
   *  ]
   */
  public static function getSessionCookies() {
    // Used to return session-cookies
    $result = array();

    // Fetch headers (waiting to be) send by php
    $headers = headers_list();
    foreach ($headers as $header)
      // We are only looking for cookies
      if (substr($header, 0, 12) === 'Set-Cookie: ') {
        // Extract cookie-settings
        $cookie   = array();
        $settings = explode(';', substr($header, 12));
        foreach ($settings as $key => $value) {
          $value              = trim($value);
          $pairs              = explode('=', $value);
          $cookie[$pairs[0]]  = $pairs[1];
        }

        // Got session-cookie?
        if (array_key_exists('PHPSESSID', $cookie))
          $result[] = array(
            'key'     => 'PHPSESSID',
            'value'   => $cookie['PHPSESSID'],
            'expires' => 0,
            'path'    => $cookie['path']
          );
        elseif (array_key_exists('authchallenge', $cookie))
          $result[] = array(
            'key'     => 'authchallenge',
            'value'   => $cookie['authchallenge'],
            'expires' => 0,
            'path'    => $cookie['path']
          );
      }

    // Return session cookies
    return $result;
  }
}
